### ISSUE TITLE
Add support for iam authentication

### ISSUE THREAD

**Issue by mdeshmu** [passren/PyDynamoDB#21]
At present, connecting superset to DynamoDB via pyDynamoDB requires us to specify access_key and secret_key that adds to operational maintenance. It would be great if the driver can take iam credentials from the environment. This can be kept behind simple boolean flag similar to what pyathena or redshift-connector already provide. Thanks.

**Comment by passren** [comment]
### @mdeshmu Good to see it can be used. This feature will be taken and release in the next minor version. Thanks for your suggestion.

**Comment by passren** [comment]
v0.4.5 released. Added Boto3 credentials support including getting IAM credentials from the environment.
[Please refer here.](https://github.com/passren/PyDynamoDB/wiki/1.-Getting-Started#credentials)
