### ISSUE TITLE
Feature request: support `assume_role_with_web_identity` in Connection

### ISSUE THREAD

**Issue by malatep** [passren/PyDynamoDB#36]
Hello, 

I'd like to raise a feature request for my use-case. 

I have Superset running in k8s and I am working with `ServiceAccount` tokens to get AWS credentials.

In order to get AWS credentials, I would need to make a call to the API [assume_role_with_web_identity](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts/client/assume_role_with_web_identity.html#) with the token I provide.

Looking into the [Connection](https://github.com/passren/PyDynamoDB/blob/1d253e751538750dae233328dd0aea669cc58ef9/pydynamodb/connection.py) class, this is not currently supported.

Related [GitHub issue](https://github.com/apache/superset/issues/25066) I opened in the Superset repo. 

Thank you

**Comment by passren** [comment]
@malatep Thanks for your feedback. I saw the issue threads you posted in the Superset Repo. Yes, currently Pydynamodb doesn't support assume_role_with_***  yet. I think your request makes sense to add to it. It won't take too long to release in the next version.

**Comment by passren** [comment]
@malatep v0.5.2 released for adding assume_role_with_web_identity. Please have a try.
