### ISSUE TITLE
Query Error in Superset with PyDynamoDB

### ISSUE THREAD

**Issue by Himanshubari08** [passren/PyDynamoDB#49]
I've connected Superset to DynamoDB using the PyDynamoDB driver. However, when I try to query DynamoDB through Superset, I find that it lacks several functions such as "split" and "replace," which prevents me from querying the tables as needed.

For example, I have a table with an "id" column that combines the database and table names. I need to split this column to get the database and table names separately.

Eg query: "SELECT substring(id,1,position('.' in id)-1) id1 FROM "my-table";"
I am getting an error: Amazon DynamoDB Error
                                   dynamodb error: Expected CaselessKeyword 'FROM', found '('  (at char 16), (line:1, col:17)

I am following the guidance provided in this document: https://github.com/passren/PyDynamoDB/wiki/5.-Superset

Can someone please help me with this?

**Comment by Himanshubari08** [comment]
Can you add support for the split or substring function ASAP as that's only what we need for now?
For eg: we have an id column with the value "abc.xyz" and we want to split "abc" as one column and "xyz" as another column with a dot as a delimiter.

We need something as there in Redshift https://docs.aws.amazon.com/redshift/latest/dg/SPLIT_PART.html

**Comment by passren** [comment]
Sure. I will give priority to your request. These functions are not supported by DynamoDB natively. Allow me to spend some time exploring whether it is possible to bypass the DynamoDB statement check.

**Comment by passren** [comment]
@Himanshubari08 The functions you asked for are supported in the new release 0.6.0. Please upgrade the lib. Have fun!

**Comment by mdeshmu** [comment]
@passren We have dot (.) as delimiter in the value of the column. I am not able to figure out how newly using newly introduced function can we split one column into two columns using dot as delimiter? I tried below query but it says invalid syntax.

SELECT SUBSTR(id,1,INSTR(id,'.')-1) col1 FROM "lakefront-ingest-stg-config-table"

example values for id column: india.mumbai

This is probably because support for INSTR is missing. can you add that?

Also, would it be possible to add inbuilt support for split_part similar to [this extension](https://github.com/nalgeon/sqlean/blob/main/docs/text.md#split_partsource-sep-part)?

**Comment by Himanshubari08** [comment]
Hi @passren, Do we have any update on this?

**Comment by passren** [comment]
@mdeshmu @Himanshubari08 I'm working on the solution for how the syntax analysis supports nested functions on columns or a better solution to handle this situation. Thanks for your patience.

**Comment by passren** [comment]
@Himanshubari08 0.6.1 released to support nested SQL statements in Superset. This should help with your issue. Please see [here](https://github.com/passren/PyDynamoDB/wiki/5.-Superset#nested-sql-supported-061)

**Comment by Himanshubari08** [comment]
Hi @passren Can you please add support for "INSTR"?
Also, would it be possible to add inbuilt support for split_part similar to (https://github.com/nalgeon/sqlean/blob/main/docs/text.md#split_partsource-sep-part)

**Comment by passren** [comment]
@Himanshubari08  yes, it does support now. You can use any SQLite native supported function in outer query, like this:
```
SELECT col1, SUBSTR(col1, INSTR(col1, '*')), col2, col3 FROM (           # Outer Query: execute on QueryDB
    SELECT ddb_col1 col1, NUMBER(ddb_col2) col2, DATETIME(ddb_col3) col3 # Inner Query: execute on DynamoDB
    FROM DDB_TABLE WHERE ddb_col1 = *
) WHERE col1 = *
```

For split_part similar function, it will come with next version release.

**Comment by mdeshmu** [comment]
@passren We tried and still throws the same error. only SUBSTR function works but when we use INSTR inside SUBSTR it doesn't work.

**Comment by passren** [comment]
> @passren We tried and still throws the same error. only SUBSTR function works but when we use INSTR inside SUBSTR it doesn't work.

Can you share the version of superset you are using?

**Comment by mdeshmu** [comment]
3.1.2

**Comment by passren** [comment]
@mdeshmu I failed to install Superset 3.1.2 on my local. Can you help to check the final SQL query generated by Apache Superset when you input the SQL query in SQL Lab? 
You can follow these steps:

**1. Execute the Query:**

Enter your SQL query (Two levels with outer and inner query) in SQL Lab and run it.

**2. View the Query History:**

After the query execution, navigate to the "Query History" tab. You can find this tab on the right side of the SQL Lab interface.

**3. Select the Query:**

In the "Query History" tab, you will see a list of queries that you have executed. Find the query you are interested in and click on it.

**4. View the Query Details:**

Once you click on the query, a pane will open showing the details of the query. This includes the final SQL that was sent to the database.
The "Query History" tab provides information about the query execution, including the raw SQL that was generated and sent to the database. This allows you to see any modifications or transformations that Superset may have applied to your original query.

**Comment by Himanshubari08** [comment]
Hi @passren , 
When I am running SUBSTR and REPLACE, then queries are running.
![Substr](https://github.com/passren/PyDynamoDB/assets/101327099/35c33b43-42ac-4e39-92a9-d2e682ca4355)

But, when I am executing INSTR, it throws an error in the superset.
![INSTR](https://github.com/passren/PyDynamoDB/assets/101327099/adc4065d-8359-43f5-98a2-c157e417522d)

It would be beneficial if you provide functionality like split_part for this.

**Comment by Himanshubari08** [comment]
@passren While running the nested query, the SQL statement is not generated in the Query History Tab.
![NestedQuery](https://github.com/passren/PyDynamoDB/assets/101327099/d34c8e20-ca1c-4b08-9bc1-ee00eec4a7c5)

**Comment by passren** [comment]
> Hi @passren , When I am running SUBSTR and REPLACE, then queries are running. ![Substr](https://private-user-images.githubusercontent.com/101327099/344893376-35c33b43-42ac-4e39-92a9-d2e682ca4355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjYwNDgsIm5iZiI6MTcyMDAyNTc0OCwicGF0aCI6Ii8xMDEzMjcwOTkvMzQ0ODkzMzc2LTM1YzMzYjQzLTQyYWMtNGUzOS05MmE5LWQyZTY4MmNhNDM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNjU1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGNlNDk5NGJiMzhmYjc3YjBhZGQzZTc3YTlmODJhODgxZGJhNjRiMGRhOTA5YzUxYWVhNjdhM2M0NWI0MTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qs-lHLiyfQpfW3B9gKi2oXOcQA01CWmVnDO4evsUUbk)
> 
> But, when I am executing INSTR, it throws an error in the superset. ![INSTR](https://private-user-images.githubusercontent.com/101327099/344893643-adc4065d-8359-43f5-98a2-c157e417522d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjYwNDgsIm5iZiI6MTcyMDAyNTc0OCwicGF0aCI6Ii8xMDEzMjcwOTkvMzQ0ODkzNjQzLWFkYzQwNjVkLTgzNTktNDNmNS05OGEyLWMxNTdlNDE3NTIyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNjU1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDg5ZDg0ZjlkNTRhNWJjMTUzMDhlZGVmYjJjZGNmNTViYzc5NmQ4YzFkMWVkNWI1ODUwOWMwZTA0MDVkYTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m4WvskoUpvRCLKUmM3Mq7kqZZPxNcJE0CVOUKiUZtzY)
> 
> It would be beneficial if you provide functionality like split_part for this.

Can you try 0.6.2 which I added sqlean.py support as default for Query DB. You can use function
[text_split](https://github.com/nalgeon/sqlean/blob/main/docs/text.md#text_splitstr-sep-n)

**Comment by Himanshubari08** [comment]
Thank you for the functionality and support. However, I'm encountering an issue with the text_split function. When I use the following code, it throws an error:

cursor.execute("select text_split('one|two|three','|',2)");
pyparsing.exceptions.ParseException: Expected CaselessKeyword 'FROM', found '('  (at char 17), (line:1, col:18)

cursor.execute('select text_split('one|two|three','|',2)');
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Could you please assist in resolving this issue? 
If possible, could we schedule a time to connect and resolve this issue together? I am flexible with timing, so please let me know if we can connect.

**Comment by passren** [comment]
@Himanshubari08 I thought you are using text_split function in Superset. I'm sorry to say that it's not supported if you use regular Cursor to fetch data from DDB directly. Please refer to [Arch](https://github.com/passren/PyDynamoDB/wiki/5.-Superset#how-it-works) here. There are two diff cursors in this lib. Regular cursor is a wrapper to interact with DDB, and Superset cursor added a middleware between DDB and Superset (aka QueryDB) which is a sqlite3 database by default. The text_split can only execute on QueryDB. So far, there is no plan to support more functions ([Supported Functions Now](https://github.com/passren/PyDynamoDB/wiki/1.-Getting-Started#datadatatime--annotation-functions) ) on regular cursor.

**Comment by mdeshmu** [comment]
It doesn't work in Superset too. 

![image](https://github.com/passren/PyDynamoDB/assets/57723564/b8baac1a-473c-4820-93e3-3cff1273106c)

**Comment by mdeshmu** [comment]
Here is full stack trace

<html>
<body>

2024-07-04 14:44:06,290:DEBUG:root:Query 6524: Running query: SELECT text_split(id,'.',1) FROM "lakefront-ingest-stg-config-table"
--
LIMIT 1001
SupersetErrorsException
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/base_api.py", line 127, in wraps
raise ex
File "/app/superset/views/base_api.py", line 121, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/app/superset/utils/core.py", line 1463, in time_function
response = func(*args, **kwargs)
File "/app/superset/views/base_api.py", line 93, in wraps
return f(self, *args, **kwargs)
File "/app/superset/utils/log.py", line 255, in wrapper
value = f(*args, **kwargs)
File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
command_result: CommandResult = command.run()
File "/app/superset/commands/sql_lab/execute.py", line 121, in run
raise ex
File "/app/superset/commands/sql_lab/execute.py", line 103, in run
status = self._run_sql_json_exec_from_scratch()
File "/app/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
raise ex
File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
return self._sql_json_executor.execute(
File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="dynamodb error: Expected CaselessKeyword 'FROM', found '('  (at char 17), (line:1, col:18)", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Amazon DynamoDB', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
2024-07-04 14:44:06,354:WARNING:superset.views.base:SupersetErrorsException
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/base_api.py", line 127, in wraps
raise ex
File "/app/superset/views/base_api.py", line 121, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/app/superset/utils/core.py", line 1463, in time_function
response = func(*args, **kwargs)
File "/app/superset/views/base_api.py", line 93, in wraps
return f(self, *args, **kwargs)
File "/app/superset/utils/log.py", line 255, in wrapper
value = f(*args, **kwargs)
File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
command_result: CommandResult = command.run()
File "/app/superset/commands/sql_lab/execute.py", line 121, in run
raise ex
File "/app/superset/commands/sql_lab/execute.py", line 103, in run
status = self._run_sql_json_exec_from_scratch()
File "/app/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
raise ex
File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
return self._sql_json_executor.execute(
File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
raise SupersetErrorsException(
superset.exceptions.SupersetErrorsException: [SupersetError(message="dynamodb error: Expected CaselessKeyword 'FROM', found '('  (at char 17), (line:1, col:18)", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Amazon DynamoDB', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]


</body>
</html>

**Comment by mdeshmu** [comment]
@passren waiting for your response.

**Comment by passren** [comment]
@mdeshmu please try this way in superset:

``` sql
SELECT text_split(id,'.',1) FROM (
    SELECT id FROM "lakefront-ingest-stg-config-table"
)
```

**Comment by Himanshubari08** [comment]
Hi @passren 
![image](https://github.com/passren/PyDynamoDB/assets/101327099/d4539e21-ec77-41d1-9464-624b5c1e2a84)
please check this

**Comment by passren** [comment]
@Himanshubari08 can you click "See more" to expand the stack trace?

**Comment by benoitcanton** [comment]
@passren I am getting the same error using version 0.7.0 and Superset 4.0.2

```
Amazon DynamoDB Error
dynamodb error: Expected table, found '('  (at char 14), (line:1, col:15)


This may be triggered by:
Issue 1002 - The database returned an unexpected error. 

See less
```

The superset logs are showing
```
superset_app          | 2024-11-07 05:11:08,002:DEBUG:botocore.client:Registering retry handlers for service: dynamodb
superset_app          | 2024-11-07 05:11:08,004:INFO:superset.sql_lab:Query 131: Running statement 1 out of 1
superset_app          | 2024-11-07 05:11:08,007:DEBUG:superset.sql_parse:Parsing with sqlparse statement: SELECT a FROM (
superset_app          | SELECT a
superset_app          |    FROM tableName
superset_app          |    WHERE a = "test"
superset_app          | )
superset_app          | 2024-11-07 05:11:08,009:DEBUG:superset.sql_parse:Parsing with sqlparse statement: SELECT a FROM (
superset_app          | SELECT a
superset_app          |    FROM tableName
superset_app          |    WHERE a = "test"
superset_app          | )
superset_app          | 2024-11-07 05:11:08,012:DEBUG:root:Query 131: Running query: SELECT a FROM (
superset_app          | SELECT a
superset_app          |    FROM tableName
superset_app          |    WHERE a = "test"
superset_app          | )
superset_app          | LIMIT 1001
superset_app          | 2024-11-07 05:11:08,012:DEBUG:superset.sql_parse:Parsing with sqlparse statement: SELECT a FROM (
superset_app          | SELECT a
superset_app          |    FROM tableName
superset_app          |    WHERE a = "test"
superset_app          | )
superset_app          | LIMIT 1001
superset_app          | 2024-11-07 05:11:08,013:DEBUG:superset.stats_logger:[stats_logger] (timing) sqllab.query.time_executing_query | 1.922119140625
superset_app          | 2024-11-07 05:11:08,013:DEBUG:superset.sql_lab:Query 131: Expected table, found '('  (at char 14), (line:1, col:15)
superset_app          | 2024-11-07 05:11:08,019:DEBUG:superset.stats_logger:[stats_logger] (incr) SqlLabRestApi.execute_sql_query.error
superset_app          | 2024-11-07 05:11:08,019:WARNING:superset.views.base:SupersetErrorsException
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1470, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 255, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/sqllab/api.py", line 409, in execute_sql_query
superset_app          |     command_result: CommandResult = command.run()
superset_app          |   File "/app/superset/commands/sql_lab/execute.py", line 121, in run
superset_app          |     raise ex
superset_app          |   File "/app/superset/commands/sql_lab/execute.py", line 103, in run
superset_app          |     status = self._run_sql_json_exec_from_scratch()
superset_app          |   File "/app/superset/commands/sql_lab/execute.py", line 163, in _run_sql_json_exec_from_scratch
superset_app          |     raise ex
superset_app          |   File "/app/superset/commands/sql_lab/execute.py", line 158, in _run_sql_json_exec_from_scratch
superset_app          |     return self._sql_json_executor.execute(
superset_app          |   File "/app/superset/sqllab/sql_json_executer.py", line 111, in execute
superset_app          |     raise SupersetErrorsException(
superset_app          | superset.exceptions.SupersetErrorsException: [SupersetError(message="dynamodb error: Expected table, found '('  (at char 14), (line:1, col:15)", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Amazon DynamoDB', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```

**Comment by passren** [comment]
@benoitcanton Did this work in the previous version? or you are first working on this?

**Comment by benoitcanton** [comment]
@passren It is the first time I am trying to connect/query a DynamoDB data source. I haven't tested the previous versions.

**Comment by passren** [comment]
@benoitcanton, thank you for the reporting. It seems Superset changed the SQL parsing from v4. It's getting an error when a string exists in the condition. I tried the numeric column in the condition, and it worked. I will review the new implementation of v4 and get back to you. Appreciate it.

**Comment by passren** [comment]
@benoitcanton I'm not sure what's happening since I can't reproduce the issue after rebooting my testing environment.

This is my test dataset:
![image](https://github.com/user-attachments/assets/fb7a632c-7efd-420f-8705-67fe88f59a90)

Used the similar nested SQL to query and got the expected result:
![image](https://github.com/user-attachments/assets/6098f8e0-a17a-44ca-b7fd-be01a9ec3d80)

Replace the quote in the condition with double-quote and it didn't get the result but still worked
![image](https://github.com/user-attachments/assets/ea5172fc-578c-4a61-92a5-3df1223081f5)


It's a bit weird but works for me.

**Comment by benoitcanton** [comment]
@passren Can you share which version of Superset you are running, please?

**Comment by passren** [comment]
> @passren Can you share which version of Superset you are running, please?

4.0.2, as you mentioned before

**Comment by benoitcanton** [comment]
@passren I have been able to get it to work. It was a silly mistake on my part... to get nested queries working **I must have** `?connector=superset` in the DynamoDb connection string.

I should have paid more attention to this document https://superset.apache.org/docs/configuration/databases/.

My working connection string looks like `dynamodb://YYYY:XXXX@dynamodb.ap-southeast-2.amazonaws.com?connector=superset`

Thanks for your help!

**Comment by passren** [comment]
@benoitcanton haha. Glad to see it works for you.
